### ISSUE TITLE
no attribute 'scalar_summary'

### ISSUE THREAD

**Issue by kmb46** [philipperemy/tensorflow-maxout#2]
When trying to execute 'python mnist_maxout_example.py MAXOUT' it shows the error below : 
AttributeError: 'module' object has no attribute 'scalar_summary'
Any suggested solution for this !

**Comment by kmb46** [comment]
> When trying to execute 'python mnist_maxout_example.py MAXOUT' it shows the error below :
> AttributeError: 'module' object has no attribute 'scalar_summary'
> Any suggested solution for this !

I've found a solution which is renaming all summary functions in the code as follow : 

-     tf.audio_summary should be renamed to tf.summary.audio
-     tf.contrib.deprecated.histogram_summary should be renamed to tf.summary.histogram
-     tf.contrib.deprecated.scalar_summary should be renamed to tf.summary.scalar
-     tf.histogram_summary should be renamed to tf.summary.histogram
-     tf.image_summary should be renamed to tf.summary.image
-     tf.merge_all_summaries should be renamed to tf.summary.merge_all
-     tf.merge_summary should be renamed to tf.summary.merge
-     tf.scalar_summary should be renamed to tf.summary.scalar
-     tf.train.SummaryWriter should be renamed to tf.summary.FileWriter

**Comment by philipperemy** [comment]
https://github.com/philipperemy/tensorflow-maxout/commit/3ba932c15f07fb53364665d3b92c9fbac8e1df8e
fixed thanks for reporting
