### ISSUE TITLE
关于正则化

### ISSUE THREAD

**Issue by liuzh-buaa** [philipperemy/tensorflow-maxout#3]
有个小问题，请问该代码中的cost是否没有考虑正则化项呢，对于应用maxout的神经网络来说，正则化项应该是怎样写的呀？

我理解的该开源代码是将神经网络每两层之间的权重放到一个大的权重矩阵W中，然后划分了不同的units从中选择了使激活值最大的一组参数，但这样的话正则化项是作用于这个大的权重矩阵还是应该怎么样呢？

求解答~

**Comment by philipperemy** [comment]
English please!

**Comment by liuzh-buaa** [comment]
你好！邮件已经收到！祝好~liuzh

**Comment by liuzh-buaa** [comment]
你好！邮件已经收到！祝好~liuzh
